---
ansible_user: "{{ lookup('env', 'USER') }}"
ansible_group: "{{ ansible_user }}"

apt_packages:
  - ack
  - ca-certificates
  - cmake
  - curl
  - direnv
  - git
  - make
  - pass
  - pipx
  - rsync
  - ssh
  - sshpass
  - tig
  - tmux
  - vim
  - wget
  - zsh

apt_app_packages:
  - gparted
  - meld
  - vlc
  - zeal

cargo_packages:
  - bat
  - bdt
  - broot
  - calc
  - clog-cli
  - coreutils
  - ddh
  - diskonaut
  - drill
  - du-dust
  - exa
  - fblog
  - fd-find
  - fend
  - git-cliff
  - git-journal
  - git-tidy
  - git-delta
  - gitui
  - grex
  - just
  - lsd
  - oxker
  - procs
  - pylyzer
  - ripgrep
  - rm-improved
  - sd
  - sniffnet
  - starship
  - watchexec-cli
  - xcp
  - xh
  - zoxide

pipx_packages:
  - csvkit
  - tsrc
