---
localhost:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local

homeservers:
  hosts:
    thinkcentre:
      ansible_host: thinkcentre.local

all:
  children:
    localhost:
    homeservers:
